template: Hello, %s!

logging:
  level: INFO
  loggers:
    com.test.dropwizard: DEBUG

# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080
